### PR TITLE
Use a new modern svg logo

### PR DESCRIPTION
**Pull request by soul-wish**
Hi! Maybe it would be better to use new svg logo in repo's `README.md` file? What do you think?

### CODE REVIEW

**Comment by ai** [comment]
@soul-wish 

1. `README.md` uses updated logo.
2. It is a special logo with padding on the left. Without this padding first code example will be too close to logo.
3. I uused a `.png` for this special version, because it was easy to edit PNG.

So, if you want, you can create a special version of logo with padding as current one. I will replace.

**Comment by soul-wish** [comment]
Oh.. Ok, thanks for your explanations. This version of logo (I mean .png) has white background. And I use black theme for github website (just a dark theme from user-styles website). Thats why your logo looks not very well. Anyway, I'm going to check what I can do with this logo tomorrow. Thanks for such a great tools!

**Comment by soul-wish** [comment]
I tried to set inline styles - but it does not work with Github's markdown engine (but works with plain markdown). It seems like GIthub's markdown interpreter replaces any inline styles with its own styles. Still searching for possible solutions.

**Comment by soul-wish** [comment]
@ai please, let me know how can I provide you with a new version of svg logo (that includes needed padding)? It looks much better than existing .png one (especially in retina display).

**Comment by ai** [comment]
Just create a SVG image with this padding

**Comment by soul-wish** [comment]
Done. Here is a [link](https://www.dropbox.com/s/awv31bcu5easkfm/logo-leftp.svg?dl=0) for new svg version with padding on the left. But this file should be placed here: `http://postcss.github.io/postcss/logo-leftp.svg`. Also, `README.md`  file was updated for using this new logo file.

**Comment by ai** [comment]
Thanks! Do you want to save your name in history? Just send a PR for `gh-pages` to `postcss/postcss` repo.

**Comment by soul-wish** [comment]
You are welcome. Sure, I submitted new [PR](https://github.com/postcss/postcss/pull/707) on `gh-pages` branch of PostCSS main repo.
PS. Just added PostCSS with few plugins for our main project and it works just great (it fixed few existing issues with maintaining our CSS codebase)! So, thanks for such an awesome set of tools.

**Comment by ai** [comment]
Done ecf7d52b3f9217661d03be466e1dda5d3896f01d

**Comment by soul-wish** [comment]
Thanks. In case you want to use **just the same** size of the logo as before - you should set `width="140"` (in this case main proportion of logo will remain the same). Now it looks just a little smaller than before. I think we can close this PR, right?

**Pull request closed without merging**
